version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  ##    
  backend:
    build: ./node-backend/
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
    depends_on:
      - mongodb
  ##
  frontend:
    build: ./react-frontend/
    ports:
      - "3300:3000"   # map localhost 3300 to 3000 in docker
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend
